version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: softball_db
    env_file: .env
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: softball_api
    env_file: .env
    environment:
      DATABASE_URL: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT:-3306}/${MYSQL_DATABASE}"
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT:-8000}:8000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: softball_web
    env_file: .env
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]

  phpmyadmin:
    image: phpmyadmin:5
    container_name: softball_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ABSOLUTE_URI: http://localhost:8081/
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
