version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: softball_api
    env_file: .env.prod
    environment:
      API_CORS_ORIGINS: https://softball-stats.casad.net
    command: >
      sh -lc 'gunicorn app.main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 --workers 2 --threads 4 --timeout 60'
    depends_on: []
    expose:
      - "8000"
    networks:
      web:
        aliases:
          - api
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: softball_web
    env_file: .env.prod
    # no host ports; Caddy handles 80/443
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
